[vgm_welcome]
order = 1
displayName = "Welcome"

pages = [
    "welcome",
    "getting_started"
]

[vgm_changelog]
order = 2
displayName = "Changelog"
pages = [
    "changelog_0_11_0",
    "changelog_0_12_0",
]

[vgm]
order = 3
displayName = "$STR_VGM_MISSION_NAME"

# Pages require a matching {pagename}.toml file.
pages = [
    "missions",
    "skills",
    "medical",
    "equipment",
]

[vgm_missions]
order = 4
displayName = ["%1 - Missions", "localize 'STR_VGM_MISSION_NAME'"]

pages = [
    "stealth",
    "scouting",
    "hints",
    "stop_and_focus",
    "alertness",
    "desperate_escape",
]
